modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="xp_trader"
version="1.0.0"
displayName="XP Trader"
logoFile="xp_trader.png"
authors="Maeiro"
description='''
Adds an XP Trader villager profession that exchanges player XP levels for emeralds.
'''

[[dependencies.xp_trader]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.xp_trader]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
